### ISSUE TITLE
Request for Pydantic v2 support

### ISSUE THREAD

**Issue by codekiln** [langchain-ai/langchain-aws#139]
Enterprise AWS customer here. Just wanted to say thank you for implementing structured output parsing for this adapter and getting it on [Structured Output table - Langchain](https://python.langchain.com/v0.2/docs/integrations/chat/#advanced-features). 

Now there's a new table of support at Langchain I'd like to get `langchain-aws` on. Versions of `langchain-core` after `0.2.23` require pydantic v2. There is a list of langchain adapters that support the pydantic v2 input to API calls here: [How to use LangChain with different Pydantic versions | 🦜️🔗 LangChain](https://python.langchain.com/v0.2/docs/how_to/pydantic_compatibility/#1-passing-pydantic-objects-to-langchain-apis) - this is a feature request to get `langchain-aws` on that list. See also [this tweet](https://x.com/LangChainAI/status/1819374670266733000) for an example of what I'd love to be able to do with langchain-aws in order to use it as well as my other providers.

Note that langchain is planning a full upgrade to pydantic v2 in September of this year: [Pydantic Migration Feedback Request · langchain-ai/langchain · Discussion #24405](https://github.com/langchain-ai/langchain/discussions/24405)

**Comment by baskaryan** [comment]
hey @codekiln, pydantic v2 should be supported for ChatBedrockConverse. see example with corresponding package versions in screenshot

also note that pydantic v2 is not required anywhere in langchain — we support pydantic v1 everywhere.

are you seeing issues when using with_structured_output with pydantic v2 classes? if so on which versions of langchain-aws?

![Screenshot 2024-08-05 at 1 27 19 PM](https://github.com/user-attachments/assets/1e8d5e2a-359e-4af0-bbdf-67415581f045)

**Comment by baskaryan** [comment]
will update https://python.langchain.com/v0.2/docs/how_to/pydantic_compatibility/ to reflect support for langchain-aws!

**Comment by codekiln** [comment]
> will update https://python.langchain.com/v0.2/docs/how_to/pydantic_compatibility/ to reflect support for langchain-aws!

Thank you @baskaryan 

> pydantic v2 should be supported for ChatBedrockConverse

I will try with `ChatBedrock`, even though I'm not using `ChatBedrockConverse`. 

Just took a look at the latter again, 

> ... use the Amazon Bedrock Converse API to create ... a chat bot that maintains a conversation over many turns and uses a persona or tone ... This means you can write code once and use it with different models.

I don't yet know what I'd use that extra layer for, given we are already maintaining chat history externally and then assembling it with Langchain to call `ChatBedrock`, and Langchain gives us the ability to write code once and use it with different models.

I will mark this as closed unless or until I find a demonstrable incompatibility.
