### ISSUE TITLE
Support numpy v2

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain-aws#147]
langchain-aws currently pinned to `^1`

**Comment by davidgilbertson** [comment]
Is this planned to be done soon? There's now commonly used packages like `thinc` that [require NumPy > 2](numpy>=2.0.0,<3.0.0) making it incompatible with `langchain-community` and `langchain-aws`, etc.

**Comment by ulgens** [comment]
+1 for the questions and its importance. Is there a particular reason for ^1 pin?
