### ISSUE TITLE
Add async streaming for Bedrock

### ISSUE THREAD

**Issue by PiotrPmr** [langchain-ai/langchain-aws#171]
### Feature request

Currently, the Bedrock `chat_model` does not support async streaming, which is odd, as the previous [PR](https://github.com/langchain-ai/langchain/pull/10393/files#diff-9874347f7fa335df661ff4089b0922b3214e08a92e9879610424522f806358f7R62) included it; seems that the async method was not added properly.

### Motivation

Without async streaming you cannot pretty much build chatbot infra.

### Your contribution

Not sure, possibly just copying-pasting what was [here](https://github.com/langchain-ai/langchain/pull/10393/files#diff-9874347f7fa335df661ff4089b0922b3214e08a92e9879610424522f806358f7R62) already?

**Comment by efriis** [comment]
transferred to `langchain-aws` for review by @3coins

**Comment by 3coins** [comment]
Closing as resolved in v0.1.17.
