### ISSUE TITLE
with_structured_output not working for Llama 3.1 models + converse

### ISSUE THREAD

**Issue by scosman** [langchain-ai/langchain-aws#179]
Thanks for adding tool/with_structured_output support to ChatBedrockConverse!

It is working great for models like mistral_large. However, the Llama 3.1 models don't work with with_structured_output, and  always return a plaintext message with ChatBedrockConverse. These models support with_structured_output on other langchain providers (groq, Ollama), and the raw models support tool calling, so they should work here as well?

There are no errors when calling with_structured_output, but the text returned in plaintext not json/tool call, and the response dict never has a "parsed" entry, just raw return.

I've tried 3.1 8B and 70B, neither works (and both works on the other platforms mentioned).

AWS docs confirming these models should support tool use: https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html

Thanks

**Comment by CyranoB** [comment]
with_structured_output doesn't seem to work for me either for the following tested model:

- anthropic.claude-3-sonnet-20240229-v1:0
- anthropic.claude-3-5-sonnet-20240620-v1:0
- anthropic.claude-3-haiku-20240307-v1:0
- mistral.mistral-large-2407-v1:0
- meta.llama3-1-70b-instruct-v1:0
- cohere.command-r-plus-v1:0

(took me a bit to realize as I have a gpt4o-mini fallback)
ParamValidationError('Parameter validation failed:\nInvalid length for parameter toolConfig.tools[0].toolSpec.description, value: 0, valid min length: 1')Traceback (most recent call last):


```
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 624, in generate
    self._generate_with_cache(
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 846, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/langchain_aws/chat_models/bedrock_converse.py", line 445, in _generate
    response = self.client.converse(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/botocore/client.py", line 1041, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eppick/projects/long_writer/.venv/lib/python3.12/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter toolConfig.tools[0].toolSpec.description, value: 0, valid min length: 1
```

Langsmith trace for Claude Sonnet 3 (same error for all models): https://smith.langchain.com/public/1ba1a190-b1c5-447b-9883-9e17277966b1/r

I also included all my depedencies:
[dependecies.txt](https://github.com/user-attachments/files/16839373/dependecies.txt)

**Comment by scosman** [comment]
@CyranoB  "mistral.mistral-large-2407-v1:0" works for me. Are you using ChatBedrockConverse on the latest version of the library?

**Comment by CyranoB** [comment]
I found the issue, I was using langchain_core.pydantic_v1 BaseModel (like in the langchain doc) instead of typing_extensions TypedDict (like in langchain-aws test case).

The following code words (including with meta.llama3-1-70b-instruct-v1:0)

```
class Division(TypedDict):
    name: str = Field(description="The division name (e.g Chapter 1, Section 1.1, etc...)")
    description: str = Field(description="one sentence description of the division")
    instructions: str = Field(description="A few sentences of instructions on what to write for this division and in what style")
    word_count: int = Field(description="The word count of the division")

class Outline(TypedDict):
    title: str = Field(description="A title for the writing")
    divisions: List[Division] = Field(description="The list of divisions")
...
model = ChatBedrockConverse(model="meta.llama3-1-70b-instruct-v1:0", temperature=0)
structured_planing_llm = model.with_structured_output(Outline)
query = "I need to write a report on the history of the internet"
prompt = load_prompt("prompts/build_outline.yaml").format(query=query)
outline = structured_planing_llm.invoke(prompt)

**Comment by scosman** [comment]
Interesting. I'm using json schema. Seems like it's not fully working with standard APIs? Will try that.

**Comment by efriis** [comment]
Could you post the version of the code using BaseModel that isn't working? That sounds like a bug

**Comment by scosman** [comment]
Amazon must have fixed this. Same test cases that failed last week now pass!
