### ISSUE TITLE
Bedrock Inference Model IDs are out of support.

### ISSUE THREAD

**Issue by keremnalbant** [langchain-ai/langchain-aws#186]
AWS recently introduced [AWS Bedrock Cross-region Inference endpoints](https://aws.amazon.com/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/). Which routes the requests to the models deployed in another regions, when dealing with low rate limits.

To use that, users need to update the `modelId` from `anthropic.claude-3-5-sonnet-20240620-v1:0` to `eu.anthropic.claude-3-5-sonnet-20240620-v1:0`.

But as LangChain splits the `modelId` by `.` to get extract the provider, it throw `Provider "eu" is not supported`.

**Comment by 3coins** [comment]
Closing, as v0.2.3 fixes support for cross-region inference endpoints.
