### ISSUE TITLE
Streaming with ChatBedrock: on_llm_new_token doesn't seem to be called

### ISSUE THREAD

**Issue by supreetkt** [langchain-ai/langchain-aws#240]
Since I've done a minor version upgrade from `v0.1.x` to `v0.2.y`, I'm having some trouble with streaming responses. Non-streaming works as expected. I'm not yet able to pinpoint the root cause, but as I'm trying to debug this, the sample code provided below isn't working as expected.

```
import boto3
from langchain_aws import ChatBedrock
from langchain.callbacks.base import BaseCallbackHandler
from langchain_core.prompts import ChatPromptTemplate

streaming = True
session = boto3.session.Session()
bedrock_client = session.client("bedrock-runtime", region_name="us-east-1")

class MyCustomHandler(BaseCallbackHandler):
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        print(f"My custom handler, token: {token}")

prompt = ChatPromptTemplate.from_messages(["Tell me a joke about {animal}"])

model = ChatBedrock(
    client=bedrock_client, 
    model_id="anthropic.claude-3-haiku-20240307-v1:0",
    streaming = streaming, 
    callbacks=[MyCustomHandler()]
)

chain = prompt | model

response = chain.invoke({"animal": "bears"})
print(response)
```

For context, using the custom callback implementation provided [here](https://python.langchain.com/docs/how_to/custom_callbacks/), I'm trying out a sample code which should print out the `on_llm_new_token` invocations as the tokens are streamed. The response should be similar to the linked documentation:

```
My custom handler, token: Here
My custom handler, token: 's
My custom handler, token:  a
My custom handler, token:  bear
...
...


content="Here's a bear joke for you:\n\nWhy don't bears wear socks?\nBecause they have bear feet!\n\nHow's that? I tried to come up with a simple, silly joke about bears. Puns involving bears' physical characteristics are a common type of bear-related humor. Let me know if you'd like to hear another bear joke!" additional_kwargs={} response_metadata={'stop_reason': 'end_turn', 'stop_sequence': None} id='xxx' usage_metadata={'input_tokens': 13, 'output_tokens': 77, 'total_tokens': 90}
```

However, I seem to only get the final response in the following code and no intermediate `on_llm_new_token` invocations. I tried the code with `ChatAnthropic` as in the documentation and it works as expected/shown there. I also looked through ChatAnthropic and [SageMakerEndpoint](https://github.com/langchain-ai/langchain-aws/blob/adcfc348c235635e910b9b9bb5c661d3829b3955/libs/aws/langchain_aws/llms/sagemaker_endpoint.py#L356) implementations. They both invoke `on_llm_new_token` but `ChatBedrock` doesn't. 

I'm not sure if this is the complete reason why streaming has stopped working since the upgrade, but it seems like something that should be fixed.

**Comment by 3coins** [comment]
@supreetkt 
Looking into this.
