### ISSUE TITLE
Meta 3B don't work in ChatBedrockConverse

### ISSUE THREAD

**Issue by idotr7** [langchain-ai/langchain-aws#258]
unable to use the: meta.llama3-2-3b-instruct-v1:0 model_id claiming it is not on-demand throughput, although it is.
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ConverseStream operation: Invocation of model ID meta.llama3-2-3b-instruct-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.
with other model id it works well.

**Comment by 3coins** [comment]
@idotr7 
For the Llama 3.2 models, only inference mode ids are supported, in your specific case, use `us.meta.llama3-2-3b-instruct-v1:0`.
<img width="657" alt="Screenshot 2024-10-28 at 4 33 06 PM" src="https://github.com/user-attachments/assets/8ee9bb76-df1f-4e09-b86b-b273b9b82304">

Here are the cross-region inference ids for all models.
https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference-support.html

**Comment by idotr7** [comment]
oh, thank you, i must have missed that in the docs.
