### ISSUE TITLE
AI21 Jamba models support

### ISSUE THREAD

**Issue by supreetkt** [langchain-ai/langchain-aws#263]
[AI21 Jamba models](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-jamba.html) require `messages` key to be sent instead of `prompt` as indicated in the following usage and error messages:

```
import boto3
from langchain_aws.llms.bedrock import BedrockLLM
from langchain_core.prompts import ChatPromptTemplate

session = boto3.session.Session()
bedrock_client = session.client("bedrock-runtime", region_name="us-east-1")

prompt = ChatPromptTemplate.from_messages(["Tell me a joke about {animal}"])
model = BedrockLLM(client=bedrock_client, model_id="ai21.jamba-instruct-v1:0")
chain = prompt | model
response = chain.invoke({"animal": "bears"})
print(response)
```

Error message:
```
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: #: required key [messages] not found#: extraneous key [prompt] is not permitted, please reformat your input and try again.
```

Currently this implementation missing and therefore Jamba models are not supported.

**Comment by 3coins** [comment]
@supreetkt 
`BedrockLLM` is going to be deprecated soon, as most model providers have started supporting messages instead of text prompts and chat models are the way to go. Would `ChatBedrockConverse` work with these models. For `ChatBedrock`, please feel free to submit a PR to fix the prompt flow for these models.

**Comment by supreetkt** [comment]
I see. If its going to be deprecated soon, we'll try to switch over to `ChatBedrockConverse` instead. Thanks!

**Comment by supreetkt** [comment]
@3coins - for parity of current functionality, we require streaming with converse API to switch over. I'm noticing this has still not been fixed. Is there an ETA on it?
