### ISSUE TITLE
Llama 3.2 with system prompt and image payload doesn't generated structured output

### ISSUE THREAD

**Issue by p0deje** [langchain-ai/langchain-aws#285]
I'm not sure if it's an issue with langchain-aws or boto3, but when llama-3.2-vision is used with _a system prompt, a structured output and an image payload_, the structured output fails to work and the JSON is returned in message contents. When at least one of the pieces is omitted (e.g. no system prompt or no image) - the structured output works perfectly fine.

To reproduce, here is the sample script - https://gist.github.com/p0deje/23231cd28ed61f1acf30fce07cbf16cd

```bash
$ python test.py
=========================
Works fine when used without image!
[{'type': 'tool_use', 'name': 'Response', 'input': {'result': 'true'}, 'id': 'tooluse_JuG13WrfQ8qEopRpFiY9GA'}]
result=True
=========================

=========================
Does not work with image:
Sure, here is a JSON for a function call with its proper arguments that best answers the given prompt:

{
    "name": "Response",
    "parameters": {
        "result": true
    }
}
None
=========================
```

**Comment by 3coins** [comment]
@p0deje 
Thanks for raising this issue, it is great that you included the code sample. I can reproduce your issue, need more data to decide if this is a problem with the ChatBedrock implementation, Bedrock service, or meta model itself. Can you try the code with the image directly with Bedrock converse API and share your results?

**Comment by 3coins** [comment]
@p0deje 
Thanks for providing all that info. It seems like a peculiarity with the way `temperature=0` setting you passed in works with tool calling in meta models. After I set the value to 1, the original gist you included seems to create the correct result. 

Results with temperature=1
```
$ python bedrock-meta-structured-with-image.py
=========================
Works fine when used without image!
[{'type': 'tool_use', 'name': 'Response', 'input': {'result': 'true'}, 'id': 'tooluse_rpQezsPTTR6CqwaOmbxiNQ'}]
result=True
=========================
=========================
Still works with image:
[{'type': 'tool_use', 'name': 'Response', 'input': {'result': True}, 'id': 'tooluse_WfS6e59bQY6mKFF0Dwzk_w'}]
result=True
```

**Comment by p0deje** [comment]
@3coins Interesting, so the same happens if I remove the system prompt, so it's essentially a combination of 
1. system prompt present
2. an image is part of a payload
3. tools are defined
4. temperature is 0

I tested in my example using `langchain-aws` instead of `boto3` and setting the temperature to 0 made no difference. In any event, any advice on how to proceed with this problem? Report to boto3 or Llama?

**Comment by 3coins** [comment]
@p0deje 
I think this seems like a candidate to check with the Llama team, it doesn't seem like there is anything we can do in langchain-aws to fix. Feel free to re-open if you find anything else.
