### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'proxies' Error

### ISSUE THREAD

**Issue by koinoue0315** [langchain-ai/langchain-aws#297]
After installing `langchain-aws 0.2.9`, I encountered the following error:
```
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'.
```

I believe this issue is the same as the one described in this URL.
https://community.openai.com/t/azureopenai-client-typeerror-client-init-got-an-unexpected-keyword-argument-proxies/1035218

Installing `langchain-aws 0.2.7` resulted in the same error.

My environment is as follows:
```
$ pip list | grep langchain
langchain                0.3.9
langchain-aws            0.2.7
langchain-community      0.3.9
langchain-core           0.3.21
langchain-openai         0.2.11
```

**Comment by 3coins** [comment]
@koinoue0315 
It's not clear from your description where that error is originating from. Can you share some sample code to reproduce this error?

**Comment by koinoue0315** [comment]
I sincerely apologize. The issue was not caused by langchain-aws but by another library.

**Comment by JuGit-pk** [comment]
This issue is related to OpenAi i guess, see this
[Link of the Issue at openai](https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332/10)

**Comment by koinoue0315** [comment]
@ayurosalina 
> can you please share what is the cause and how to solve it? because i have the same problem. Thanks

In my case, the cause of the issue was `Anthropic`. Updating the `Anthropic` version from `0.34.1` to 0.40.0` resolved the problem.

**Comment by RoyKiran** [comment]
downgrade httpx version to 0.27.0
