### ISSUE TITLE
Querying Llama3 70b using BedrockChat returns empty response if prompt is long

### ISSUE THREAD

**Issue by fedor-intercom** [langchain-ai/langchain-aws#31]
Hello,

I have posted this [bug](https://github.com/langchain-ai/langchain/issues/21037) on the main repo. However it seems that `from langchain_community.chat_models import BedrockChat` has been deprecated.

I have tried with `from langchain_aws.chat_models import BedrockChat` and I am facing the same issue. So cross posting as it might be more relevant here.

TL;DR: Querying Llama3 with BedrockChat returns an empty string if long query. Short queries like "What is the capital of China?" does return the expected answer. If I pass the long query directly in the AWS Console, it works fine.

Example:
```python
from langchain.chains import LLMChain
from langchain.prompts import HumanMessagePromptTemplate
from langchain.prompts.chat import ChatPromptTemplate
from langchain_aws.chat_models import BedrockChat 
import langchain

langchain.debug = True

def get_llama3_bedrock(
    model_id="meta.llama3-70b-instruct-v1:0",
    max_gen_len=2048,
    top_p=0.0,
    temperature=0.0,
):
    model_kwargs = {
        "top_p": top_p,
        "max_gen_len": max_gen_len,
        "temperature": temperature,
    }
    return BedrockChat(model_id=model_id, model_kwargs=model_kwargs)

prompt_poem = """
This is a poem by William Blake

============
Never seek to tell thy love
Love that never told can be 
For the gentle wind does move
Silently invisibly

I told my love I told my love 
I told her all my heart 
Trembling cold in ghastly fears
Ah she doth depart

Soon as she was gone from me
A traveller came by
Silently invisibly 
O was no deny 
============

What did the lady do?
"""
langchain_prompt = ChatPromptTemplate.from_messages([
        HumanMessagePromptTemplate.from_template(prompt_poem)
        ]
)
print("Response 1:", LLMChain(llm=get_llama3_bedrock(), prompt=langchain_prompt).run(dict()))
#Responds: ''

prompt_simple_question = """What is the capital of China?"""
langchain_prompt = ChatPromptTemplate.from_messages([
        HumanMessagePromptTemplate.from_template(prompt_simple_question)
        ]
)
print("Response 2:", LLMChain(llm=get_llama3_bedrock(), prompt=langchain_prompt).run(dict()))
#Responds: 'Beijing.'


```

Versions:
python 3.11.7

langchain==0.1.16
langchain-aws==0.1.2
langchain-core==0.1.46
langchain-text-splitters==0.0.1

**Comment by anaszil** [comment]
I think "<|begin_of_text|>" should only appear in the begining of the prompt, not in the begining of each message.

Check the template [here](https://github.com/meta-llama/llama-recipes#:~:text=%3C%7Cbegin_of_text%7C%3E%3C%7Cstart_header_id%7C%3Esystem%3C%7Cend_header_id%7C%3E%0A%0A%7B%7B%20system_prompt,user_message_2%20%7D%7D%3C%7Ceot_id%7C%3E%3C%7Cstart_header_id%7C%3Eassistant%3C%7Cend_header_id%7C%3E)

**Comment by bqmackay** [comment]
@anaszil I can confirm that putting  "<|begin_of_text|>" at the beginning does work as intended. 

When using the Llama3 8b model without the monkey patch, the model will continue a fictitious conversation.

**Comment by fedor-intercom** [comment]
Thanks, @anaszil and @bqmackay, you are right :). 
It's reflected in the PR.
