### ISSUE TITLE
Provider cohere model does not support chat.

### ISSUE THREAD

**Issue by WaterKnight1998** [langchain-ai/langchain-aws#33]
`langchain-aws = "~= 0.1.2"`

Does not support Cohere CommandR chat models:

https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-cohere-command-r-plus.html

**Comment by 3coins** [comment]
See #238 for using `ChatModelConverse` or `ChatBedrock(beta_use_converse_api=True)`. Please subscribe to #238 for any updates to the cohere support.
