### ISSUE TITLE
Token Counts not used from Bedrock response.

### ISSUE THREAD

**Issue by NAPTlME** [langchain-ai/langchain-aws#41]
I would like to track the token counts (input/output) for my Bedrock calls in a similar fashion to this [example](https://python.langchain.com/docs/modules/callbacks/token_counting/) for langchain-openai using callbacks.

These token counts are present in the header (or chunk data for streaming), but they are not captured by langchain-aws.

This [PR](https://github.com/langchain-ai/langchain-aws/pull/20) addresses this issue.

Thanks.

**Comment by 3coins** [comment]
Fixed in v0.1.5.
