### ISSUE TITLE
Claude v3 models are not supported by BedrockLLM

### ISSUE THREAD

**Issue by GxWwT** [langchain-ai/langchain-aws#60]
from langchain_aws import BedrockLLM

llm = BedrockLLM(model_id="anthropic.claude-3-sonnet-20240229-v1:0", region_name='us-east-1')

**Comment by lgb861213** [comment]
it show the following error:
  Claude v3 models are not supported by this LLM.Please use `from langchain_community.chat_models import BedrockChat` instead. (type=value_error)

**Comment by rollwagen** [comment]
Duplicate #35

**Comment by 3coins** [comment]
Please migrate to ChatBedrock class for using Claude v3 models.
