### ISSUE TITLE
Official Anthropic function calling support?

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain-aws#65]
Anthropic announced GA support for tools today (5/30): https://www.anthropic.com/news/tool-use-ga

Is this meant to be supported? I saw some PRs mentioned related to tool use, but the following code returns an empty list:

```python
from langchain_aws import ChatBedrock  # langchain-aws v0.1.4 (latest)
from langchain_core.messages import HumanMessage
from langchain_community.tools import DuckDuckGoSearchRun

llm = ChatBedrock(
    model_id="anthropic.claude-3-sonnet-20240229-v1:0",
    region_name="us-east-1",
)

search = DuckDuckGoSearchRun()

tools = [search]

# llm with tools
llm_with_tools = llm.bind_tools(tools)

messages = [
    ("system", "You are a helpful assistant."),
    ("human", "What is LangChain Tool Calling?")
]

llm_with_tools.invoke(messages).tool_calls
```

Output:
```
[]
```

**Comment by austinmw** [comment]
https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html#tool-use-examples

**Comment by laithalsaadoon** [comment]
@3coins what are your thoughts on adding Converse API support? Would we want a different class like ConverseBedrock maybe?

**Comment by austinmw** [comment]
Ideally the implementation would allow for traditional LangChain tools to be passed, and they could be translated to toolSpec's. For example, I hope this will work in the future implementation:

```python
from langchain_core.tools import tool

@tool
def calculator(a: int, b: int) -> int:
    """Perform multiplication."""
    return a * b

llm = ChatBedrock(
    model_id="anthropic.claude-3-sonnet-20240229-v1:0",
    region_name="us-east-1",
)

tools = [calculator]

# Bind tools to the LLM
llm_with_tools = llm.bind_tools(tools)


messages = [
    HumanMessage(content="What is the result of 42 multiplied by 3? Use the calculator tool."),
]

result = llm_with_tools.invoke(messages)
```

**Comment by thiagotps** [comment]
Function calling works with the `invoke_model` method too. At least for claude.

**Comment by AlinJiang** [comment]
Quote from https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-bedrock-new-converse-api/
> The Converse API provides a consistent experience that works with Amazon Bedrock models, removing the need for developers to manage any model-specific implementation. With this API, you can write a code once and use it seamlessly with different models on Amazon Bedrock.

Since the new Converse API provides the long-waited unified interface for all bedrock models and official tool use support, it makes sense to switch from invoke API to converse API as soon as possible.

**Comment by AlinJiang** [comment]
In the new implementation on top of Converse API, we should also expose the complete response payload, including metadata like "stop_reason", such info becomes crucial now when working with function calling and agents.

**Comment by thiagotps** [comment]
> @3coins what are your thoughts on adding Converse API support? Would we want a different class like ConverseBedrock maybe?

Given that there is a on going pull request implementing function calling via `invoke_model`, I also think that it is a good idea to have  a separate class for the `converse` method.

**Comment by adamdbrw** [comment]
I found this issue as we want to use Bedrock models for our langchain work for robotics, so switching to converse API would be perfect. Right now it is more convenient to work with OpenAI.

**Comment by yingzwang** [comment]
#70 is still based on the legacy tool use of Claude, which is not recommended by Anthropic and does not work well with Claude 3.

**Comment by zhichenggeng** [comment]
@austinmw @yingzwang Correct me if I'm wrong. This code snippet should be using the official function calling from claude. If it is not claude 3 then it will use the old XML parsing way.
https://github.com/langchain-ai/langchain-aws/blob/c873bb2203ca357a2c565aebf7585fe0a67f5138/libs/aws/langchain_aws/chat_models/bedrock.py#L615-L633
